package lesson1.checkpoint_1_4.frame_1_4_5;

public enum Color {
BLACK, BLUE, RED, GREEN, YELLOW, PINK, ORANGE, BROWN, WHITE, GREY, AUBERGINE, 
DARK_BLUE,DARK_RED, DARK_GREEN, LIGHT_BLUE, LIGHT_GREEN; 
}
